apiVersion: v1
kind: PersistantVolume
metadata: 
  name: ebs-static
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 30Gi
  csi:
    driver: ebs.csi.aws.com
    fstype: ext4
    volumeHandle: vol-08eb5282ad7560049