apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: ebs-static
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  volumeName: ebs-static
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1 
kind: Pod
metadata: 
  name: ebs-static
  labels: 
    purpose: "ebs-static-demo"
spec:
  nodeSelector: 
    topology.kubernetes.io/zone: us-east-1b

  containers: 
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-staic
---
apiVersion: v1 
kind: Service
metadata:
  name: nginx
spec: 
  type: LoadBalancer
  selector:
    purpose: "ebs-static-demo"
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30008