apiVersion: v1 
kind: PersistentVolumeClaim
metadata: 
  name: ebs-static-claim
spec:
  storageClassName: ""
  volumeName: ebs-static
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20GI



