apiVersion: v1
kind: Pod
metadata: 
  name: labels
  namespace: expense
  labels: 
    project: expense
    component: backend
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx