kind: Pod
apiVersion: v1
metadata: 
  name: env
  namespace: expense
spec: 
  containers:
  - name: nginx
    image: nginx
    env: #we can supply the env variables run time
    - name: cource
      value: Devops
    - name: duration
      value: 120hrs
    - name: trainer
      value: Siva