apiVersion: v1
kind: Pod
metadata:
  name: resources
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      #soft limit
      requests:
        memory: "64Mi"
        cpu: "250m"
      #hard limit (hard limit can be equal to soft limit but should not be less than soft limit)
      limits:
        memory: "128Mi"
        cpu: "500m"  #processer