kind: Pod
apiVersion: v1
metadata: 
  name: resources
  namespace: expense
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      #soft limit
      requests:
        memory: "64mi"
        cpu: "100m"
      #hard limit
      limits:
        memory: "128mi"
        cpu: "200m"
    # env:
    # - name: cource
    #   value: Devops
    # - name: trainer
    #   value: Siva
        

