apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    project: expense
    environment: Dev
    component: backend
    version: "1.0"
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---
apiVersion: v1
kind: Pod
metadata: 
  name: backend
  labels: 
    project: expense
    environment: Dev
    component: backend
    version: "1.0"
spec:
  containers:
  - name: nginx
    image: nginx
  
  

