apiVersion: v1
kind: Service
metadata:
  name: backed
spec:
  selector:
    project: expense
    environment: Dev
    component: backend
    version: "1.0"
  ports:
  - protocol: TCP
    port: 80
    targetport: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    project: expense
    environment: Dev
    component: backend
    version: "1.0"
spec:
  containers: 
  - name: nginx
    image: nginx