apiVersion: v1
kind: Service
metadata: 
  name: nginx-np
spec:
  type: NodePort
  selector:
    project: metro-bank
    environment: Dev
    component: frontend
    version: "1.0"
  ports:  
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007
---
apiVersion: v1
kind: Pod
metadata: 
  name: frontend
  labels: 
    project: metro-bank
    environment: Dev
    component: frontend
    version: "1.0"
spec:
  containers:
  - name: nginx
    image: nginx

