kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
  labels:
    app: backend
    tier: app 
    purpose: Deployment
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: backend
      tier: app
      purpose: Deployment
  template:
    metadata:
      labels: 
        app: backend
        tier: app
        purpose: Deployment
    spec:
      containers:
      - name: nginx
        image: lakshman143/deployment:2.0
        ports:
        - containerPort: 80

---
kind: Service
apiVersion: v1 
metadata:   
  name: nginx
spec: 
  type: LoadBalancer
  selector:  #labels are used as selectors
    app: backend
    tier: app
    purpose: Deployment
  ports:
  - protocol: TCP
    port: 80    #service port
    targetPort: 80
    nodePort: 30007



