kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
  labels:
    app: backend
    tier: app 
    purpose: Deployment
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: backend
      tier: app
      purpose: Deployment
    template:
      metadata:
        labels: 
          app: backend
          tier: app
          purpose: Deployment
      spec:
        containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
          - containerPort: 80


