apiVersion: v1
kind: Service
metadata:
  name: nginx
  demo: statefulset
  labels:
    app: nginx
spec:
  selector:
    app: nginx
    demo: statefulset
  ports:
  - port: 80
    name: web
  clusterIP: None
  